Add homework for lesson #42
petroleg/robot_dreams_homework pull request #28
Opened 2023-08-06 21:33 UTC by petroleg

Please provide code review and comment if necessary:)

2023-08-07 08:31 UTC, acman requested changes
Don't see usage of print_purchase

2023-08-07 08:31 UTC, acman commented on djangoProject/user/tasks.py
> +def print_purchases(user_id):
use this functions somewhere

2023-08-07 10:03 UTC, petroleg commented on djangoProject/user/tasks.py
> +def print_purchases(user_id):
Done

2023-08-08 16:02 UTC, acman approved these changes
GJ!

2023-08-09 07:39 UTC, merged